// Code generated by sql2gorm. DO NOT EDIT.
package model

import (
	"time"
)

type Request struct {
	Email string `json:"email" binding:"required"`
}

// table in the database
type User struct {
	UserID         int       `gorm:"column:user_id;primary_key;AUTO_INCREMENT"`
	Name           string    `gorm:"column:name;NOT NULL"`
	Email          string    `gorm:"column:email;unique;NOT NULL"`
	HashedPassword string    `gorm:"column:hashed_password;NOT NULL"`
	Profile        string    `gorm:"column:profile"`
	Role           string    `gorm:"column:role;NOT NULL"`
	IsActive       int       `gorm:"column:is_active;default:1"`
	IsVerify       int       `gorm:"column:is_verify;default:0"`
	CreateAt       time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP"`
}

func (m *User) TableName() string {
	return "user"
}

